"""environment table

Revision ID: 26e46ba47c05
Revises: 
Create Date: 2020-11-21 19:55:35.871162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e46ba47c05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Environemnt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Environemnt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('temperature', sa.REAL(), nullable=True),
    sa.Column('humidity', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('environment')
    # ### end Alembic commands ###
